[Rainmeter]
Update=-1
BackgroundMode=1
;DefaultWindowX=#WORKAREAWIDTH#/2 - 200
;DefaultWindowY=#WORKAREAHEIGHT#/2 - 115
Group=all
DefaultAlwaysOnTop=-2

[Metadata]
Name=Theme settings
Author=Immanuel Smith
Information=Switch currently used theme
License=Creative Commons BY-NC-SA 3.0
Version=1.0

[Variables]
@include=#@#settings.inc
scale=0.69
@include2=#@#Styles\styles.inc
title=
title2=THEME - #ThemeName#
width=400
height=230
autoscale=0
@include3=#@#Styles\background_local.inc

[MeasureUser]
Measure=Plugin
Plugin=SysInfo
SysInfoType=USER_NAME
UpdateDivider=-1

[meterMask1]
Meter=Shape
X=(5*#scale#)
Y=(30*#scale#)
MeterStyle=StyleMask

[meterBorder1]
Meter=Shape
MeterStyle=StyleBorder

[meterData1]
Meter=String
MeterStyle=StyleButton
Container=meterMask1
Text=#ThemeName1#
LeftMouseUpAction=[!WriteKeyValue Variables Theme 1 "#@#settings.inc"][!RefreshApp]


[meterMask2]
Meter=Shape
X=(10*#scale#)R
Y=0r
MeterStyle=StyleMask

[meterBorder2]
Meter=Shape
MeterStyle=StyleBorder

[meterData2]
Meter=String
MeterStyle=StyleButton
Container=meterMask2
Text=#ThemeName2#
LeftMouseUpAction=[!WriteKeyValue Variables Theme 2 "#@#settings.inc"][!RefreshApp]

[meterMask3]
Meter=Shape
X=(5*#scale#)
Y=(8*#scale#)R
MeterStyle=StyleMask

[meterBorder3]
Meter=Shape
MeterStyle=StyleBorder

[meterData3]
Meter=String
MeterStyle=StyleButton
Container=meterMask3
Text=#ThemeName3#
LeftMouseUpAction=[!WriteKeyValue Variables Theme 3 "#@#settings.inc"][!RefreshApp]

[meterMask4]
Meter=Shape
X=(10*#scale#)R
Y=0r
MeterStyle=StyleMask

[meterBorder4]
Meter=Shape
MeterStyle=StyleBorder

[meterData4]
Meter=String
MeterStyle=StyleButton
Container=meterMask4
Text=#ThemeName4#
LeftMouseUpAction=[!WriteKeyValue Variables Theme 4 "#@#settings.inc"][!RefreshApp]

[meterMask5]
Meter=Shape
X=(5*#scale#)
Y=(8*#scale#)R
MeterStyle=StyleMask

[meterBorder5]
Meter=Shape
MeterStyle=StyleBorder

[meterData5]
Meter=String
MeterStyle=StyleButton
Container=meterMask5
Text=#ThemeName5#
LeftMouseUpAction=[!WriteKeyValue Variables Theme 5 "#@#settings.inc"][!RefreshApp]

[meterMask6]
Meter=Shape
X=(10*#scale#)R
Y=0r
MeterStyle=StyleMask

[meterBorder6]
Meter=Shape
MeterStyle=StyleBorder

[meterData6]
Meter=String
MeterStyle=StyleButton
Container=meterMask6
Text=#ThemeName6#
LeftMouseUpAction=[!WriteKeyValue Variables Theme 6 "#@#settings.inc"][!RefreshApp]

[meterMask7]
Meter=Shape
X=(5*#scale#)
Y=(8*#scale#)R
MeterStyle=StyleMask

[meterBorder7]
Meter=Shape
MeterStyle=StyleBorder

[meterData7]
Meter=String
MeterStyle=StyleButton
Container=meterMask7
Text=#ThemeName7#
LeftMouseUpAction=[!WriteKeyValue Variables Theme 7 "#@#settings.inc"][!RefreshApp]

[meterMask8]
Meter=Shape
X=(10*#scale#)R
Y=(0r
MeterStyle=StyleMask

[meterBorder8]
Meter=Shape
MeterStyle=StyleBorder

[meterData8]
Meter=String
MeterStyle=StyleButton
Container=meterMask8
Text=#ThemeName0#
LeftMouseUpAction=[!WriteKeyValue Variables Theme 0 "#@#settings.inc"][!RefreshApp]

[meterMask9]
Meter=Shape
X=(5*#scale#)
Y=(8*#scale#)R
MeterStyle=StyleMask

[meterBorder9]
Meter=Shape
MeterStyle=StyleBorder

[meterData9]
Meter=String
MeterStyle=StyleButton
Container=meterMask9
Text=REFRESH
LeftMouseUpAction=[!RefreshApp]


[meterMask10]
Meter=Shape
X=(10*#scale#)R
Y=0r
MeterStyle=StyleMask

[meterBorder10]
Meter=Shape
MeterStyle=StyleBorder

[meterData10]
Meter=String
MeterStyle=StyleButton
Container=meterMask10
Text=CUSTOMIZE THEME
LeftMouseUpAction=[!ActivateConfig "Refract\Theme" "customize.ini"]
