[Rainmeter]
Update=-1
BackgroundMode=1
;DefaultWindowX=#WORKAREAWIDTH#/2 - 200
;DefaultWindowY=#WORKAREAHEIGHT#/2 - 115
Group=all
DefaultAlwaysOnTop=-2

[Metadata]
Name=Custom Theme Settings
Author=Immanuel Smith
Information=Change custom theme colors
License=Creative Commons BY-NC-SA 3.0
Version=1.0

[Variables]
@include=#@#settings.inc
scale=0.69
@include2=#@#Styles\styles.inc
title=
title2=Customize - [#ThemeName]
width=400
height=230
autoscale=0
@include3=#@#Styles\background_local.inc


[measureData9]
Measure=Plugin
Plugin=InputText
FontSize=(12*#scale#)
X=(106*#scale#)
Y=(90*#scale#)
DefaultValue=#ThemeName#
Command1=!WriteKeyValue Variables ThemeName[#Theme]" "$UserInput$" "#@#settings.inc"
Command2=!Refresh #CURRENTCONFIG#

[measureData10]
Measure=Plugin
Plugin=InputText
FontSize=(12*#scale#)
X=(106*#scale#)
Y=(90*#scale#)
DefaultValue=#scale#
InputNumber=1
Command1=!WriteKeyValue Variables scale" "$UserInput$" "#@#settings.inc"
Command2=[!RefreshApp]

[meterMask1]
Meter=Shape
X=(5*#scale#)
Y=(30*#scale#)
MeterStyle=StyleMask

[meterBorder1]
Meter=Shape
MeterStyle=StyleBorder

[meterData1]
Meter=String
MeterStyle=StyleButton
Container=meterMask1
Text=NORMAL TEXT
LeftMouseUpAction=["#@#Addons\RainRGB\RainRGB4.exe" "VarName=NormalTextColor[#Theme]" "Filename=#@#settings.inc"][!RefreshApp]


[meterMask2]
Meter=Shape
X=(10*#scale#)R
Y=0r
MeterStyle=StyleMask

[meterBorder2]
Meter=Shape
MeterStyle=StyleBorder

[meterData2]
Meter=String
MeterStyle=StyleButton
Container=meterMask2
Text=Headline TEXT
LeftMouseUpAction=["#@#Addons\RainRGB\RainRGB4.exe" "VarName=HighlightTextColor[#Theme]" "Filename=#@#settings.inc"][!RefreshApp]


[meterMask3]
Meter=Shape
X=(5*#scale#)
Y=(10*#scale#)R
MeterStyle=StyleMask

[meterBorder3]
Meter=Shape
MeterStyle=StyleBorder

[meterData3]
Meter=String
MeterStyle=StyleButton
Container=meterMask3
Text=GRAPHS
LeftMouseUpAction=["#@#Addons\RainRGB\RainRGB4.exe" "VarName=GraphColor[#Theme]" "Filename=#@#settings.inc"][!RefreshApp]


[meterMask4]
Meter=Shape
X=(10*#scale#)R
Y=0r
MeterStyle=StyleMask

[meterBorder4]
Meter=Shape
MeterStyle=StyleBorder

[meterData4]
Meter=String
MeterStyle=StyleButton
Container=meterMask4
Text=ACCENT COLOR
LeftMouseUpAction=["#@#Addons\RainRGB\RainRGB4.exe" "VarName=AccentColor[#Theme]" "Filename=#@#settings.inc"][!RefreshApp]

[meterMask5]
Meter=Shape
X=(5*#scale#)
Y=(10*#scale#)R
MeterStyle=StyleMask

[meterBorder5]
Meter=Shape
MeterStyle=StyleBorder

[meterData5]
Meter=String
MeterStyle=StyleButton
Container=meterMask5
Text=RENAME THEME
LeftMouseUpAction=!CommandMeasure "measureData9" "ExecuteBatch 1-2"

[meterMask6]
Meter=Shape
X=(10*#scale#)R
Y=0r
MeterStyle=StyleMask

[meterBorder6]
Meter=Shape
MeterStyle=StyleBorder

[meterData6]
Meter=String
MeterStyle=StyleButton
Container=meterMask6
Text=SCALE = #scale#
LeftMouseUpAction=!CommandMeasure "measureData10" "ExecuteBatch 1-2"

[meterMask7]
Meter=Shape
X=(5*#scale#)
Y=(10*#scale#)R
MeterStyle=StyleMask

[meterBorder7]
Meter=Shape
MeterStyle=StyleBorder

[meterData7]
Meter=String
MeterStyle=StyleButton
Container=meterMask7
Text=CHOOSE THEME
LeftMouseUpAction=[!ActivateConfig "Refract\Theme" "choose.ini"]

[StyleIndicator]
W=(12*#scale#)
H=(12*#scale#)
ImageName=box.png

[meterIndicator1]
Meter=Image
X=(20*#scale#)
Y=(38*#scale#)
MeterStyle=StyleIndicator
SolidColor=#NormalTextColor#

[meterIndicator2]
Meter=Image
X=(220*#scale#)
Y=0r
MeterStyle=StyleIndicator
SolidColor=#HighlightTextColor#

[measureColor1]
Measure=String
String=#GraphColor#.
Substitute=",255.":",200"

[meterIndicator3]
Meter=Image
X=(20*#scale#)
Y=(42*#scale#)r
MeterStyle=StyleIndicator
SolidColor=[measureColor1]

[meterIndicator4]
Meter=Image
X=(220*#scale#)
Y=0r
MeterStyle=StyleIndicator
SolidColor=#AccentColor#


