[Rainmeter]
Update=1000
BackgroundMode=1
Group=all
DefaultAlwaysOnTop=-2

[Metadata]
Name=Top processes list
Author=Immanuel Smith
Information=Notes widget
License=Creative Commons BY-NC-SA 3.0
Version=1.0

[measureColor2]
Measure=String
String=#NormalTextColor#.
Substitute=",255.":",235"

[measureColor3]
Measure=String
String=#NormalTextColor#.
Substitute=",255.":",215"

[measureColor4]
Measure=String
String=#NormalTextColor#.
Substitute=",255.":",195"

[measureColor5]
Measure=String
String=#NormalTextColor#.
Substitute=",255.":",175"

[StyleListText]
FontColor=#NormalTextColor#
FontFace=Moongloss Display Thick
AntiAlias=1
StringCase=Upper
FontSize=(11*#scale#)
Text=%1[\10]%2[\10]%3[\10]%4[\10]%5[\10]
ClipString=1
InlineSetting=Color | [measureColor2]
InlinePattern=^.*\n(.*)\n
InlineSetting2=Color | [measureColor3]
InlinePattern2=^.*\n.*\n(.*)\n
InlineSetting3=Color | [measureColor4]
InlinePattern3=^.*\n.*\n.*\n(.*)\n
InlineSetting4=Color | [measureColor5]
InlinePattern4=^.*\n.*\n.*\n.*\n(.*)\n

[Variables]
title=
title2=
width=1900
height=200
autoscale=0
@include=#@#Styles\background.inc

[MeasureTotalRAM]
Measure=PhysicalMemory
Total=1
UpdateDivider=3600

[MeasureCPU1]
Measure=Plugin
Plugin=UsageMonitor
Alias=CPU
Index=1

[MeasureCPU2]
Measure=Plugin
Plugin=UsageMonitor
Alias=CPU
Index=2

[MeasureCPU3]
Measure=Plugin
Plugin=UsageMonitor
Alias=CPU
Index=3

[MeasureCPU4]
Measure=Plugin
Plugin=UsageMonitor
Alias=CPU
Index=4

[MeasureCPU5]
Measure=Plugin
Plugin=UsageMonitor
Alias=CPU
Index=5

[MeasureCPU1Num]
Measure=Calc
Formula=MeasureCPU1

[MeasureCPU2Num]
Measure=Calc
Formula=MeasureCPU2

[MeasureCPU3Num]
Measure=Calc
Formula=MeasureCPU3

[MeasureCPU4Num]
Measure=Calc
Formula=MeasureCPU4

[MeasureCPU5Num]
Measure=Calc
Formula=MeasureCPU5

[MeasureRAM1]
Measure=Plugin
Plugin=UsageMonitor
Alias=RAMSHARED
Index=1

[MeasureRAM2]
Measure=Plugin
Plugin=UsageMonitor
Alias=RAM
Index=2

[MeasureRAM3]
Measure=Plugin
Plugin=UsageMonitor
Alias=RAM
Index=3

[MeasureRAM4]
Measure=Plugin
Plugin=UsageMonitor
Alias=RAM
Index=4

[MeasureRAM5]
Measure=Plugin
Plugin=UsageMonitor
Alias=RAM
Index=5

[MeasureRAM1Num]
Measure=Calc
Formula=MeasureRAM1/MeasureTotalRAM

[MeasureRAM2Num]
Measure=Calc
Formula=MeasureRAM2/MeasureTotalRAM

[MeasureRAM3Num]
Measure=Calc
Formula=MeasureRAM3/MeasureTotalRAM

[MeasureRAM4Num]
Measure=Calc
Formula=MeasureRAM4/MeasureTotalRAM

[MeasureRAM5Num]
Measure=Calc
Formula=MeasureRAM5/MeasureTotalRAM


[MeasureIO1]
Measure=Plugin
Plugin=UsageMonitor
Alias=IO
Index=1

[MeasureIO2]
Measure=Plugin
Plugin=UsageMonitor
Alias=IO
Index=2

[MeasureIO3]
Measure=Plugin
Plugin=UsageMonitor
Alias=IO
Index=3

[MeasureIO4]
Measure=Plugin
Plugin=UsageMonitor
Alias=IO
Index=4

[MeasureIO5]
Measure=Plugin
Plugin=UsageMonitor
Alias=IO
Index=5

[MeasureIO1Num]
Measure=Calc
Formula=MeasureIO1/1024

[MeasureIO2Num]
Measure=Calc
Formula=MeasureIO2/1024

[MeasureIO3Num]
Measure=Calc
Formula=MeasureIO3/1024

[MeasureIO4Num]
Measure=Calc
Formula=MeasureIO4/1024

[MeasureIO5Num]
Measure=Calc
Formula=MeasureIO5/1024

[measureColor3]
Measure=String
String=#GraphColor#.
Substitute=",255.":",80"

[meterTitleCPU]
Meter=String
MeterStyle=StyleSecondText
StringCase=Upper
X=(10*#scale#)
Y=(10*#scale#)
W=(100*#scale#)
H=(20*#scale#)
FontSize=12
FontColor=#HighlightTextColor#
Text=Cpu usage

[meterCPUs]
Meter=String
MeterStyle=StyleListText
StringCase=Upper
MeasureName=MeasureCPU1
MeasureName2=MeasureCPU2
MeasureName3=MeasureCPU3
MeasureName4=MeasureCPU4
MeasureName5=MeasureCPU5
X=0r
Y=(40*#scale#)
W=(200*#scale#)
H=(100*#scale#)
Text=%1[\10]%2[\10]%3[\10]%4[\10]%5[\10]


[meterCPUVals]
Meter=String
MeterStyle=StyleListText
StringCase=Upper
MeasureName=MeasureCPU1Num
MeasureName2=MeasureCPU2Num
MeasureName3=MeasureCPU3Num
MeasureName4=MeasureCPU4Num
MeasureName5=MeasureCPU5Num
X=(40*#scale#)R
Y=0r
W=(40*#scale#)
H=(100*#scale#)
Text=%1[\10]%2[\10]%3[\10]%4[\10]%5[\10]
ClipString=1
StringAlign=Right

[meterDivider1]
Meter=Shape
X=(40*#scale#)r
Y=(10*#scale#)
Shape=Line 0,0,0,(110*#scale#) | StrokeWidth (1*#scale#) | Stroke Color #AccentColor#

[meterTitleRam]
Meter=String
MeterStyle=styleSecondText
StringCase=Upper
X=(40*#scale#)R
Y=(10*#scale#)
W=(100*#scale#)
H=(20*#scale#)
FontSize=12
FontColor=#HighlightTextColor#
Text=memory usage

[meterRAMs]
Meter=String
MeterStyle=StyleListText
StringCase=Upper
MeasureName=MeasureRAM1
MeasureName2=MeasureRAM2
MeasureName3=MeasureRAM3
MeasureName4=MeasureRAM4
MeasureName5=MeasureRAM5
X=0r
Y=(40*#scale#)
W=(200*#scale#)
H=(100*#scale#)
Text=%1[\10]%2[\10]%3[\10]%4[\10]%5[\10]
ClipString=1

[meterRAMVals]
Meter=String
MeterStyle=StyleListText
StringCase=Upper
MeasureName=MeasureRAM1Num
MeasureName2=MeasureRAM2Num
MeasureName3=MeasureRAM3Num
MeasureName4=MeasureRAM4Num
MeasureName5=MeasureRAM5Num
X=(50*#scale#)R
Y=0r
W=(40*#scale#)
H=(100*#scale#)
Text=%1[\10]%2[\10]%3[\10]%4[\10]%5[\10]
ClipString=1
Percentual=1
StringAlign=Right

[meterDivider2]
Meter=Shape
X=(40*#scale#)r
Y=(10*#scale#)
Shape=Line 0,0,0,(110*#scale#) | StrokeWidth (1*#scale#) | Stroke Color #AccentColor#

[meterTitleIO]
Meter=String
MeterStyle=StyleSecondText
StringCase=Upper
X=(40*#scale#)R
Y=(10*#scale#)
W=(100*#scale#)
H=(20*#scale#)
FontSize=12
FontColor=#HighlightTextColor#
Text=I/O usage

[meterIOs]
Meter=String
MeterStyle=StyleListText
StringCase=Upper
MeasureName=MeasureIO1
MeasureName2=MeasureIO2
MeasureName3=MeasureIO3
MeasureName4=MeasureIO4
MeasureName5=MeasureIO5
X=0r
Y=(40*#scale#)
W=(200*#scale#)
H=(100*#scale#)
Text=%1[\10]%2[\10]%3[\10]%4[\10]%5[\10]
ClipString=1

[meterIOVals]
Meter=String
MeterStyle=StyleListText
StringCase=Upper
MeasureName=MeasureIO1Num
MeasureName2=MeasureIO2Num
MeasureName3=MeasureIO3Num
MeasureName4=MeasureIO4Num
MeasureName5=MeasureIO5Num
X=(40*#scale#)R
Y=0r
W=(60*#scale#)
H=(100*#scale#)
Text=%1[\10]%2[\10]%3[\10]%4[\10]%5[\10]
ClipString=1
;StringAlign=Right
