[Rainmeter]
Update=1000
BackgroundMode=1
Group=all
DefaultAlwaysOnTop=-2
OnRefreshAction=[!CommandMeasure MeasureLogicalProcessors "Run"]

[Metadata]
Name=CPU usage
Author=smithxtt
Information=CPU usage
License=Creative Commons BY-NC-SA 3.0
Version=1.0


[Variables]
title=
title2=
unit=%
autoscale=0
width=(630*#scale#)
height=(630*#scale#)
autoscale=0
min_radius = (54*#scale#)
factor = (2.7*#scale#)
@include=#@#Styles\background.inc

[MeasureLogicalProcessors]
Measure=Plugin
Plugin=RunCommand
Parameter=powershell.exe -command "Get-WmiObject -class Win32_processor | Select NumberOfLogicalProcessors -expandproperty NumberOfLogicalProcessors"
OutputType=ANSI
RegExpSubstitute=1
;Substitute="(?siU)^.*NumberOfLogicalProcessors=([\d]{1,2})":"\1","#CRLF#":""
FinishAction=[!CommandMeasure "meterScript" "Initialize()"]


[MeasureCPUName]
Measure=Registry
RegHKey=HKEY_LOCAL_MACHINE
RegKey=HARDWARE\DESCRIPTION\System\CentralProcessor\0
RegValue=ProcessorNameString
UpdateDivider=-1

[measureColor2]
Measure=String
String=#GraphColor#.
Substitute=",255.":",160"

[measureColor3]
Measure=String
String=#GraphColor#.
Substitute=",255.":",80"



[MeterCPUName]
Meter=String
MeasureName=MeasureCPUName
FontColor=#HighlightTextColor#
FontFace=Moongloss Display Thick
AntiAlias=1
x=(180*#scale#)
y=(20*#scale#)
w=(740*#scale#)
h=(30*#scale#)
FontSize=(11*#scale#)
Text=%1
StringCase=Upper
Clipstring=1

[MeasureUptime]
Measure=Uptime
Format="%4!i! DAYS, %3!02i!:%2!02i!:%1!02i!"


[meterUptime]
Meter=String
MeterStyle=StyleSecondText
StringCase=Upper
MeasureName=MeasureUptime
FontColor=#GraphColor#
X=(5*#scale#)
Y=(610*#scale#)
W=(740*#scale#)
H=(30*#scale#)
FontSize=(11*#scale#)
Text=UPTIME: %1
Clipstring=1


@include=cores.inc


[meterShapes]
Meter=Shape
X=(300*#scale#)
Y=(270*#scale#)
DynamicVariables=1
Shape=Path MyPath | StrokeWidth (3*#scale#) | Stroke Color #GraphColor# | Fill Color 0,0,0,0
Shape2=Path MyPath2 | StrokeWidth (2*#scale#) | Stroke Color [measureColor2] | Fill Color 0,0,0,0
Shape3=Path MyPath3 | StrokeWidth (1*#scale#) | Stroke Color [measureColor3] | Fill Color 0,0,0,0

MyPath = 
MyPath2 = 
MyPath3 = 

[meterFrame]
Meter=Shape
X=0
Y=0
UpdateDivider=-1
Shape=Path MyPath | StrokeWidth (1*#scale#) | Stroke Color #AccentColor# | Fill Color 0,0,0,0
Shape2=Path MyPath2 | StrokeWidth (1*#scale#) | Stroke Color #AccentColor# | Fill Color 0,0,0,0


MyPath =  (1*#scale#),(12*#scale#) | LineTo (595*#scale#),(12*#scale#) | LineTo (595*#scale#),(30*#scale#)
MyPath2= (1*#scale#),(610*#scale#) | LineTo (1*#scale#),(630*#scale#) | LineTo (595*#scale#),(630*#scale#)


[meterScript]
Measure=Script
ScriptFile=heatmap.lua




