[Rainmeter]
Update=60000
BackgroundMode=1
Group=all
DefaultAlwaysOnTop=-2

[Metadata]
Name=Calendar
Author=Immanuel Smith
Information=Calendar widget
License=Creative Commons BY-NC-SA 3.0
Version=1.0

[Variables]
@include=#@#settings.inc
scale=0.69
@include2=#@#Styles\styles.inc
title=
title2=
width=400
height=280
autoscale=0
@include3=#@#Styles\background_local.inc

[styleCal]
StringAlign=CenterCenter
StringCase=None
FontColor=#AccentColor#
FontFace=Moongloss Display Thick
w=(25*#scale#)
H=(20*#scale#)
AntiAlias=1
ClipString=1
FontSize=(12*#scale#)

[styleCalSelect]
StringAlign=CenterCenter
StringCase=None
FontColor=#GraphColor#
FontFace=Moongloss Display Thick
w=(25*#scale#)
H=(20*#scale#)
AntiAlias=1
ClipString=1
FontSize=(12*#scale#)


[styleCalUnselect]
StringAlign=CenterCenter
StringCase=None
FontColor=#NormalTextColor#
FontFace=Moongloss Display Thick
w=(25*#scale#)
H=(20*#scale#)
AntiAlias=1
ClipString=1
FontSize=(12*#scale#)
SolidColor=255,255,255,0


[meterData]
Measure=Script
ScriptFile=#@#Scripts\calendar.lua

[MeterBorder]
Meter=Shape
MeterStyle=StyleMeterBorderTop


[meterSelector]
;THIS WILL BE MODIFIED BY CALENDAR.LUA
Meter=Shape
Shape=Rectangle 5,5, 25, 25,2 | Fill Color #GraphColor#

[meterL1]
Meter=String
MeterStyle=styleCal
StringCase=None
X=(34*#scale#)
Y=(25*#scale#)
Text=Su

[meterL2]
Meter=String
MeterStyle=styleCal
StringCase=None
X=(31*#scale#)R
Y=0r
Text=Mo

[meterL3]
Meter=String
MeterStyle=styleCal
StringCase=None
X=(31*#scale#)R
Y=0r
Text=Tu

[meterL4]
Meter=String
MeterStyle=styleCal
StringCase=None
X=(31*#scale#)R
Y=0r
Text=We

[meterL5]
Meter=String
MeterStyle=styleCal
StringCase=None
X=(31*#scale#)R
Y=0r
Text=Th

[meterL6]
Meter=String
MeterStyle=styleCal
StringCase=None
X=(31*#scale#)R
Y=0r
Text=Fr

[meterL7]
Meter=String
MeterStyle=styleCal
StringCase=None
X=(31*#scale#)R
Y=0r
Text=Sa



[meterD1]
Meter=String
MeterStyle=styleCalUnselect
StringCase=None
X=(34*#scale#)
Y=17R
Text=.

[meterD2]
Meter=String
MeterStyle=styleCalUnselect
StringCase=None
X=(31*#scale#)R
Y=0r
Text=.

[meterD3]
Meter=String
MeterStyle=styleCalUnselect
StringCase=None
X=(31*#scale#)R
Y=0r
Text=.

[meterD4]
Meter=String
MeterStyle=styleCalUnselect
StringCase=None
X=(31*#scale#)R
Y=0r
Text=

[meterD5]
Meter=String
MeterStyle=styleCalUnselect
StringCase=None
X=(31*#scale#)R
Y=0r
Text=

[meterD6]
Meter=String
MeterStyle=styleCalUnselect
StringCase=None
X=(31*#scale#)R
Y=0r
Text=

[meterD7]
Meter=String
MeterStyle=styleCalUnselect
StringCase=None
X=(31*#scale#)R
Y=0r
Text=

[meterD8]
Meter=String
MeterStyle=styleCalUnselect
StringCase=None
X=(34*#scale#)
Y=17R
Text=

[meterD9]
Meter=String
MeterStyle=styleCalUnselect
StringCase=None
X=(31*#scale#)R
Y=0r
Text=

[meterD10]
Meter=String
MeterStyle=styleCalUnselect
StringCase=None
X=(31*#scale#)R
Y=0r
Text=

[meterD11]
Meter=String
MeterStyle=styleCalUnselect
StringCase=None
X=(31*#scale#)R
Y=0r
Text=

[meterD12]
Meter=String
MeterStyle=styleCalUnselect
StringCase=None
X=(31*#scale#)R
Y=0r
Text=

[meterD13]
Meter=String
MeterStyle=styleCalUnselect
StringCase=None
X=(31*#scale#)R
Y=0r
Text=

[meterD14]
Meter=String
MeterStyle=styleCalUnselect
StringCase=None
X=(31*#scale#)R
Y=0r
Text=

[meterD15]
Meter=String
MeterStyle=styleCalUnselect
StringCase=None
X=(34*#scale#)
Y=17R
Text=

[meterD16]
Meter=String
MeterStyle=styleCalUnselect
StringCase=None
X=(31*#scale#)R
Y=0r
Text=

[meterD17]
Meter=String
MeterStyle=styleCalUnselect
StringCase=None
X=(31*#scale#)R
Y=0r
Text=

[meterD18]
Meter=String
MeterStyle=styleCalUnselect
StringCase=None
X=(31*#scale#)R
Y=0r
Text=

[meterD19]
Meter=String
MeterStyle=styleCalUnselect
StringCase=None
X=(31*#scale#)R
Y=0r
Text=

[meterD20]
Meter=String
MeterStyle=styleCalUnselect
StringCase=None
X=(31*#scale#)R
Y=0r
Text=

[meterD21]
Meter=String
MeterStyle=styleCalUnselect
StringCase=None
X=(31*#scale#)R
Y=0r
Text=

[meterD22]
Meter=String
MeterStyle=styleCalUnselect
StringCase=None
X=(34*#scale#)
Y=(17*#scale#)R
Text=

[meterD23]
Meter=String
MeterStyle=styleCalUnselect
StringCase=None
X=(31*#scale#)R
Y=0r
Text=

[meterD24]
Meter=String
MeterStyle=styleCalUnselect
StringCase=None
X=(31*#scale#)R
Y=0r
Text=

[meterD25]
Meter=String
MeterStyle=styleCalUnselect
StringCase=None
X=(31*#scale#)R
Y=0r
Text=

[meterD26]
Meter=String
MeterStyle=styleCalUnselect
StringCase=None
X=(31*#scale#)R
Y=0r
Text=

[meterD27]
Meter=String
MeterStyle=styleCalUnselect
StringCase=None
X=(31*#scale#)R
Y=0r
Text=

[meterD28]
Meter=String
MeterStyle=styleCalUnselect
StringCase=None
X=(31*#scale#)R
Y=0r
Text=

[meterD29]
Meter=String
MeterStyle=styleCalUnselect
StringCase=None
X=(34*#scale#)
Y=(17*#scale#)R
Text=

[meterD30]
Meter=String
MeterStyle=styleCalUnselect
StringCase=None
X=(31*#scale#)R
Y=0r
Text=

[meterD31]
Meter=String
MeterStyle=styleCalUnselect
StringCase=None
X=(31*#scale#)R
Y=0r
Text=

[meterD32]
Meter=String
MeterStyle=styleCalUnselect
StringCase=None
X=(31*#scale#)R
Y=0r
Text=

[meterD33]
Meter=String
MeterStyle=styleCalUnselect
StringCase=None
X=(31*#scale#)R
Y=0r
Text=

[meterD34]
Meter=String
MeterStyle=styleCalUnselect
StringCase=None
X=(31*#scale#)R
Y=0r
Text=

[meterD35]
Meter=String
MeterStyle=styleCalUnselect
StringCase=None
X=(31*#scale#)R
Y=0r
Text=

[meterD36]
Meter=String
MeterStyle=styleCalUnselect
StringCase=None
X=(34*#scale#)
Y=(17*#scale#)R
Text=

[meterD37]
Meter=String
MeterStyle=styleCalUnselect
StringCase=None
X=(31*#scale#)R
Y=0r
Text=

[meterD38]
Meter=String
MeterStyle=styleCalUnselect
StringCase=None
X=(31*#scale#)R
Y=0r
Text=

[meterD39]
Meter=String
MeterStyle=styleCalUnselect
StringCase=None
X=(31*#scale#)R
Y=0r
Text=

[meterD40]
Meter=String
MeterStyle=styleCalUnselect
StringCase=None
X=(31*#scale#)R
Y=0r
Text=

[meterD41]
Meter=String
MeterStyle=styleCalUnselect
StringCase=None
X=(31*#scale#)R
Y=0r
Text=

[meterD42]
Meter=String
MeterStyle=styleCalUnselect
StringCase=None
X=(31*#scale#)R
Y=0r
Text=
