[Rainmeter]
Author=lynxNZL

[Variables]
@includeSettings=#ROOTCONFIGPATH#SETTINGS.inc
@includeStyles=#@#Styles.inc
@includeMeasures=#@#Measures.inc
Width=#FullScreen_Width#
Height=#FullScreen_Height#

[Metadata]
Description=FullScreen cmd.exe skin

;=====================
;METERS
;=====================

[MeterBorder]
Meter=IMAGE
SolidColor=#Color#,#Transparency#
W=#Width#
H=#Height#
X=0
Y=0

[MeterBG]
Meter=IMAGE
SolidColor=0,0,0,255
W=(#Width# - 20)
H=(#Height# - 43)
X=10
Y=33

[MeterIcon]
Meter=IMAGE
ImageName=#@#Images\cmdicon.png
X=12
Y=10
LeftMouseUpAction=!Execute ["#ROOTCONFIGPATH#SETTINGS.inc"]
ToolTipText="Click to open Settings"

[MeterClose]
Meter=BUTTON
ImageAlpha=245
SolidColor=0,0,0,1
X=(#Width#-45-9)
Y=1
ButtonImage=#@#Images\close.png
LeftMouseUpAction=!DeactivateConfig

[MeterWindow]
Meter=BUTTON
ImageAlpha=245
SolidColor=0,0,0,1
X=-26r
Y=1
ButtonImage=#@#Images\window.png
LeftMouseUpAction=!ActivateConfig #CURRENTCONFIG#

[MeterMinimise]
Meter=BUTTON
ImageAlpha=245
SolidColor=0,0,0,1
X=-27r
Y=1
ButtonImage=#@#Images\minimise.png
LeftMouseUpAction=!Refresh
ToolTipText="Click to Refresh"

[MeterTitle]
Meter=STRING
StringAlign=Center
FontFace=Segoe UI
X=((#Width#/2)+9)
Y=6
ClipString=1
W=#Width#
H=33
Text="C:\Windows\system32\cmd.exe"
FontSize=11
AntiAlias=1

[MeterOS]
Meter=STRING
MeasureName=MeasureOS
MeasureName2=MeasureOSArch
MeasureName3=MeasureVersion
MeasureName4=MeasureBuild
MeasureName5=MeasureServicePack
MeterStyle=StyleText
X=10
Y=33
ClipString=1
W=#Width#
H=#FontSize#
Text="Microsoft  %1  %2-Bit  [Version %3.%4] %5"

[MeterText]
Meter=String
MeterStyle=StyleText
X=0r
Y=12r
ClipString=1
W=#Width#
H=#FontSize#
Text="(c)  2013  Microsoft  Corporation.  All  rights  reserved."

[Meter1]
Meter=STRING
MeterStyle=StyleText
X=10
Y=5R
Text=" "
@includeMeter1=#ROOTCONFIGPATH#Meters\#Meter1#.inc

[Meter2]
Meter=STRING
MeterStyle=StyleText
X=10
Y=5R
Text=" "
@includeMeter2=#ROOTCONFIGPATH#Meters\#Meter2#.inc

[Meter3]
Meter=STRING
MeterStyle=StyleText
X=10
Y=5R
Text=" "
@includeMeter3=#ROOTCONFIGPATH#Meters\#Meter3#.inc

[Meter4]
Meter=STRING
MeterStyle=StyleText
X=10
Y=5R
Text=" "
@includeMeter4=#ROOTCONFIGPATH#Meters\#Meter4#.inc

[Meter5]
Meter=STRING
MeterStyle=StyleText
X=10
Y=5R
Text=" "
@includeMeter4=#ROOTCONFIGPATH#Meters\#Meter5#.inc

[Meter6]
Meter=STRING
MeterStyle=StyleText
X=10
Y=5R
Text=" "
@includeMeter4=#ROOTCONFIGPATH#Meters\#Meter6#.inc

[Meter7]
Meter=STRING
MeterStyle=StyleText
X=10
Y=5R
Text=" "
@includeMeter4=#ROOTCONFIGPATH#Meters\#Meter7#.inc

[Meter8]
Meter=STRING
MeterStyle=StyleText
X=10
Y=5R
Text=" "
@includeMeter4=#ROOTCONFIGPATH#Meters\#Meter8#.inc

[Meter9]
Meter=STRING
MeterStyle=StyleText
X=10
Y=5R
Text=" "
@includeMeter4=#ROOTCONFIGPATH#Meters\#Meter9#.inc

[MeterJoke1]
Meter=STRING
MeterStyle=StyleText
MeasureName=MeasureUserName
X=10
Y=5R
Text="%UserProfile%> cd c:\windows\system32"

[MeterJoke2]
Meter=STRING
MeterStyle=StyleText
X=0r
Y=0R
Text="C:\WINDOWS\system32> del *"

[MeterJoke3]
Meter=STRING
MeterStyle=StyleText
X=0r
Y=0R
Text="C:\WINDOWS\system32\*, Are you sure (Y/N)? y"

[MeterJoke4]
Meter=STRING
MeterStyle=StyleText
X=0r
Y=0R
Text=" :("

[MeterEndText]
Meter=STRING
MeterStyle=StyleText
X=10
Y=0R
Text="%UserProfile%>_"
