[Rainmeter]
Author=lynxNZL
MiddleMouseUpAction=!Execute ["#ROOTCONFIGPATH#SETTINGS.inc"]

[Metadata]
Description=Greeting Box for first use

[Variables]
@includeSettings=#ROOTCONFIGPATH#SETTINGS.inc
@includeStyles=#@#Styles.inc
@includeMeasures=#@#Measures.inc
Width=350
Height=400

;I had planned to make this a dynamic box where you could select options, but I dont think it would have been worth the effort.

;=====================
;METERS
;=====================
[MeterBorder]
Meter=IMAGE
SolidColor=#Color#,#Transparency#
W=(#Width#+20)
H=(#Height#+43)
X=0
Y=0

[MeterBG]
Meter=IMAGE
SolidColor=0,0,0,255
W=(#Width#)
H=(#Height#)
X=10
Y=33

[MeterIcon]
Meter=IMAGE
ImageName=#@#Images\cmdicon.png
X=12
Y=10
LeftMouseUpAction=!Execute ["#ROOTCONFIGPATH#SETTINGS.inc"]
ToolTipText="Click to open Settings"

[MeterClose]
Meter=BUTTON
ImageAlpha=245
SolidColor=0,0,0,1
X=(#Width#-25-9)
Y=1
ButtonImage=#@#Images\close.png
LeftMouseUpAction=!DeactivateConfig

[MeterMaximise]
Meter=BUTTON
ImageAlpha=245
SolidColor=0,0,0,1
X=-26r
Y=1
ButtonImage=#@#Images\maximise.png

[MeterMinimise]
Meter=BUTTON
ImageAlpha=245
SolidColor=0,0,0,1
X=-27r
Y=1
ButtonImage=#@#Images\minimise.png

[MeterTitle]
Meter=STRING
FontFace=Segoe UI
StringAlign=Right
X=-5r
Y=6
ClipString=1
W=(#Width#-125)
H=33
Text="C:\Windows\system32\cmd.exe"
FontSize=11
AntiAlias=1

[MeterOS]
Meter=STRING
MeasureName=MeasureOS
MeasureName2=MeasureOSArch
MeasureName3=MeasureVersion
MeasureName4=MeasureBuild
MeasureName5=MeasureServicePack
MeterStyle=StyleText
X=10
Y=33
ClipString=1
W=#Width#
H=#FontSize#
Text="Microsoft  %1  %2-Bit  [Version %3.%4] %5."

[MeterWindowsText]
Meter=String
MeterStyle=StyleText
X=0r
Y=#FontSize#r
ClipString=1
W=#Width#
H=#FontSize#
Text="(c)  2013  Microsoft  Corporation.  All  rights  reserved."

[MeterUserNameGreeting]
Meter=STRING
MeterStyle=StyleText
X=10
Y=5R
Text="%UserProfile%> WELCOME.bat.exe.jpg"
ClipString=1
W=#Width#
H=(#FontSize#+2)

[Meter0]
Meter=STRING
MeterStyle=StyleText
X=10
Y=5R
FontColor=250,150,0
Text="===WELCOME MESSAGE==="

[Meter1]
Meter=STRING
MeterStyle=StyleText
X=10
Y=0R
FontColor=150,250,0
Text="Hey there :)"

[Meter2]
Meter=STRING
MeterStyle=StyleText
X=10
Y=0R
FontColor=150,250,0
Text="Thanks for trying out my skin!"

[Meter3]
Meter=STRING
MeterStyle=StyleText
X=10
Y=0R
FontColor=150,250,0
Text="heh, "skin.""

[Meter4]
Meter=STRING
MeterStyle=StyleText
X=10
Y=0R
FontColor=150,250,0
Text="Anyway, here's some handy TIPS:"

[Meter5]
Meter=STRING
MeterStyle=StyleText
X=10
Y=10R
FontColor=250,150,0
Text="--TIPS--"

[Meter6]
Meter=STRING
MeterStyle=StyleText
X=10
Y=10R
FontColor=250,250,0
Text="Middle-Click anywhere for SETTINGS"

[Meter7]
Meter=STRING
MeterStyle=StyleText
X=10
Y=0R
FontColor=150,250,0
Text="or left-click the cmd icon up the top."

[Meter7.5]
Meter=STRING
MeterStyle=StyleText
X=10
Y=0R
FontColor=150,250,0
Text="PLEASE read SETTINGS to ensure it will work."

[Meter7.6]
Meter=STRING
MeterStyle=StyleText
X=10
Y=0R
FontColor=150,250,0
Text="You will need to adjust the WeatherCode etc..."

[Meter8]
Meter=STRING
MeterStyle=StyleText
X=10
Y=10R
FontColor=150,250,0
Text="Click the minimise button to refresh the skin."

[Meter9]
Meter=STRING
MeterStyle=StyleText
X=10
Y=0R
FontColor=150,250,0
Text="Maximise button will maximise the skin. Yeah!"

[Meter10]
Meter=STRING
MeterStyle=StyleText
X=10
Y=10R
FontColor=150,250,0
Text="I didnt quite customise the fullscreen part."

[Meter11]
Meter=STRING
MeterStyle=StyleText
X=10
Y=0R
FontColor=150,250,0
Text="so it only maximises it at the moment. Sorry :("

[Meter12]
Meter=STRING
MeterStyle=StyleText
X=10
Y=10R
FontColor=250,250,0
Text="Make sure to read/edit SETTINGS to your liking"

[Meter13]
Meter=STRING
MeterStyle=StyleText
X=10
Y=10R
FontColor=150,250,0
Text="That's about it. I hope you enjoy it :)"

[Meter14]
Meter=STRING
MeterStyle=StyleText
X=10
Y=10R
FontColor=150,250,0
Text="PS. Feel free to close this welcome message now."