[Rainmeter]
Update=30

[Metadata]
Name=RKS Illusions
Author=Ritukalpa Saikia
Information=A simple rainmeter experiment using square patterns
License=
Version=1.0

;Variables------------------------------

[Variables]
Skincolor=0,0,0
Skinalpha=200

;measures------------------------------

[MeasureTime1]
Measure=Time
Averagesize=30

[Measuresec]
Measure=Calc
Formula=MeasureTime1 * 30

;Styles----------------------------------------

[Style]
x=0
y=0
W=300
h=300
Solid=1
Antialias=1

;meters-------------------------------------

[Metercircle]
Meter=Roundline
Meterstyle=Style
Linestart=130
Linelength=125
Linecolor=0,0,0,200
Startangle=(Rad(0))
Rotationangle=(Rad(360))
x=-5
y=-5
Hidden=1

[Metersquaremov]
Meter=Rotator
Measurename=Measuresec
Valueremainder=1800
Startangle=0
Rotationangle=(Rad(360))
Imagename=sq.png
Imagealpha=#Skinalpha#
Imagetint=#Skincolor#
W=155
H=151
Offsetx=77.5
Offsety=75.5
x=30
y=30

[Metersquaremovl]
Meter=Rotator
Measurename=Measuresec
Valueremainder=1800
Startangle=0
Rotationangle=(-Rad(360))
Imagename=sq.png
Imagealpha=#Skinalpha#
Imagetint=#Skincolor#
W=155
H=151
Offsetx=77.5
Offsety=75.5
x=30
y=30


[Metersquaremov1]
Meter=Rotator
Measurename=Measuresec
Valueremainder=1800
Startangle=0
Rotationangle=(Rad(360))
Imagename=sq.png
Imagealpha=#Skinalpha#
Imagetint=#Skincolor#
W=155
H=151
Offsetx=77.5
Offsety=75.5
x=107.5
y=30

[Metersquaremovl1]
Meter=Rotator
Measurename=Measuresec
Valueremainder=1800
Startangle=0
Rotationangle=(-Rad(360))
Imagename=sq.png
Imagealpha=#Skinalpha#
Imagetint=#Skincolor#
W=155
H=151
Offsetx=77.5
Offsety=75.5
x=107.5
y=30


[Metersquaremov2]
Meter=Rotator
Measurename=Measuresec
Valueremainder=1800
Startangle=0
Rotationangle=(Rad(360))
Imagename=sq.png
Imagealpha=#Skinalpha#
Imagetint=#Skincolor#
W=155
H=151
Offsetx=77.5
Offsety=75.5
x=30
y=105.5

[Metersquaremovl2]
Meter=Rotator
Measurename=Measuresec
Valueremainder=1800
Startangle=0
Rotationangle=(-Rad(360))
Imagename=sq.png
Imagealpha=#Skinalpha#
Imagetint=#Skincolor#
W=155
H=151
Offsetx=77.5
Offsety=75.5
x=30
y=105.5


[Metersquaremov3]
Meter=Rotator
Measurename=Measuresec
Valueremainder=1800
Startangle=0
Rotationangle=(Rad(360))
Imagename=sq.png
Imagealpha=#Skinalpha#
Imagetint=#Skincolor#
W=155
H=151
Offsetx=77.5
Offsety=75.5
x=107.5
y=105.5

[Metersquaremovl3]
Meter=Rotator
Measurename=Measuresec
Valueremainder=1800
Startangle=0
Rotationangle=(-Rad(360))
Imagename=sq.png
Imagealpha=#Skinalpha#
Imagetint=#Skincolor#
W=155
H=151
Offsetx=77.5
Offsety=75.5
x=107.5
y=105.5
