[WebShortcut]
w=(40)*#scaledpi#
h=(40)*#scaledpi#
X=5R
y=r

LeftMouseUpAction=!ToggleConfig "BigSur\Web\#currentsection#" "Item3.ini"
ToolTipText=#currentsection#
imagename=#@#\Graphics\Thumbs\Web\#currentsection#.png




[Netflix]
Meter=Image
MeterStyle=WebShortcut
x=(225)*#scaledpi#
y=(40)*#scaledpi#
[Google]
Meter=Image
MeterStyle=WebShortcut
[Amazon]
Meter=Image
MeterStyle=WebShortcut
[YouTube]
Meter=Image
MeterStyle=WebShortcut
[Facebook]
Meter=Image
MeterStyle=WebShortcut
[Reddit]
Meter=Image
MeterStyle=WebShortcut
[Twitter]
Meter=Image
MeterStyle=WebShortcut
[Imdb]
Meter=Image
MeterStyle=WebShortcut
[Pinterest]
Meter=Image
MeterStyle=WebShortcut
[Fandom]
Meter=Image
MeterStyle=WebShortcut
x=(225)*#scaledpi#
y=(1)*#scaledpi#R


[Craigslist]
Meter=Image
MeterStyle=WebShortcut
[eBay]
Meter=Image
MeterStyle=WebShortcut
[DeviantArt]
Meter=Image
MeterStyle=WebShortcut
[Indeed]
Meter=Image
MeterStyle=WebShortcut
[Nytimes]
Meter=Image
MeterStyle=WebShortcut
imagetint=#textcolor2#
[Msnbc]
Meter=Image
MeterStyle=WebShortcut
[cnn]
Meter=Image
MeterStyle=WebShortcut
[weatherdotcom]
Meter=Image
MeterStyle=WebShortcut
[businessinsider]
Meter=Image
MeterStyle=WebShortcut
x=(225)*#scaledpi#
y=(1)*#scaledpi#R
[theguardian]
Meter=Image
MeterStyle=WebShortcut
[msn]
Meter=Image
MeterStyle=WebShortcut
imagetint=#textcolor2#
[usatoday]
Meter=Image
MeterStyle=WebShortcut
[cnet]
Meter=Image
MeterStyle=WebShortcut
[spotify]
Meter=Image
MeterStyle=WebShortcut
imagetint=#textcolor2#
[9gag]
Meter=Image
MeterStyle=WebShortcut
imagetint=#textcolor2#


[geektyper]
Meter=Image
MeterStyle=WebShortcut
[wikipedia]
Meter=Image
MeterStyle=WebShortcut
imagetint=#textcolor2#

[Webmd]
Meter=Image
MeterStyle=WebShortcut
x=(225)*#scaledpi#
y=(1)*#scaledpi#R

[Yandex]
Meter=Image
MeterStyle=WebShortcut
[Github]
Meter=Image
MeterStyle=WebShortcut
[Engadget]
Meter=Image
MeterStyle=WebShortcut